import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {ReactFlowProvider} from "reactflow";
import {RootStoreProvider} from "@/stores/root-store-provider";
import {NextUIProvider} from "@nextui-org/react";
import Toasts from "@/components/toasts";
import {Providers} from "@/app/providers";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Providers>
            {children}
            <Toasts></Toasts>
        </Providers>
        </body>
        </html>
    );
}
